=== TheJuanitoLearnsShow/PuppyDataMapper/src/schemas/data-mapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example/mapper">
  <xs:element name="mapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="inputs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="input" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="type" type="xs:string"/>
                    <xs:element name="referenceName" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="maps">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="map" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="inputs">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="input" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                  <xs:element name="source" type="xs:string"/>
                                  <xs:element name="formula" type="xs:string"/>
                                  <xs:element name="comments" type="xs:string" minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="outputType">
                        <xs:simpleType >
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="string"/>
                                <xs:enumeration value="date"/>
                            </xs:restriction> 
                        </xs:simpleType> 
                    </xs:element>
                    <xs:element name="customLogic" type="xs:string"/>
                  </xs:sequence> 
                </xs:complexType> 
              </xs:element> 
            </xs:sequence> 
          </xs:complexType> 
        </xs:element> 
      </xs:sequence> 
    </xs:complexType> 
  </xs:element> 
</xs:schema>

=== TheJuanitoLearnsShow/PuppyDataMapper/src/PuppyDataMapper.Tests/SampleMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:mapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example/mapper ../schemas/data-mapper.xsd"
    xmlns:m="http://example/mapper" >
    <name>From Test to Stat Entry</name>
    <description>
        Maps from a test taken to a score to be added to the statistical software.
    </description>
    <inputs>
        <input>
            <name>Test Record</name>
            <type>Test</type>
            <referenceName>Test</referenceName>
        </input>
        <input>
            <name>Population Test Statistics</name>
            <type>TestSummary</type>
            <referenceName>Stats</referenceName>
        </input>
    </inputs>
    <maps>
        <map>
            <name>Adjusted Score</name>
            <inputs>
                <input>
                    <source>Test</source>
                    <formula>DateTaken</formula>
                </input>
                <input>
                    <source>Test</source>
                    <formula>Score</formula>
                </input>
                <input>
                    <source>Stats</source>
                    <formula>Scores.Avg</formula>
                    <comments>The avg of the whole population</comments>
                </input>
            </inputs>
            <outputType>string</outputType>
            <customLogic>divide score by average of population, multiplied by the number of days ago
                that DateTaken</customLogic>
        </map>
        <map>
            <name>End of Month</name>
            <inputs>
                <input>
                    <source>Test</source>
                    <formula>DateTaken</formula>
                    <comments>Must be the month where the test was taken</comments>
                </input>
            </inputs>
            <outputType>date</outputType>
            <customLogic>the last date of the month when the test was taken</customLogic>
        </map>
    </maps>
</m:mapper>

=== TheJuanitoLearnsShow/PuppyDataMapper/src/PuppyDataMapper.Tests/Mapping-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xml-transformations/data-mapper-to-html.xsl"?>
<mapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example/mapper ../schemas/data-mapper.xsd"
    xmlns="http://example/mapper"
    xmlns:m="http://example/mapper" generate-code="true">
    <name>From Test to Stat Entry</name>
    <comments>
        Maps from a test taken to a score to be added to the statistical software.
    </comments>
    <outputType>StatEntry</outputType>
    <inputs>
        <input>
            <name>Test Record</name>
            <type>Test</type>
            <referenceName>test</referenceName>
        </input>
        <input>
            <name>Population Test Statistics</name>
            <type>TestSummary</type>
            <referenceName>Stats</referenceName>
        </input>
    </inputs>
    <maps>
        <map>
            <name>Adjusted Score</name>
            <outputTo>AdjustedScore</outputTo>
            <outputType>string</outputType>
            <comments>divide score by average of population, multiplied by the number of days ago
                that DateTaken</comments>
            <inputs generate-code="true">
                <input>
                    <source>test</source>
                    <formula>DateTaken</formula>
                </input>
                <input>
                    <source>test</source>
                    <formula>Score</formula>
                </input>
                <input>
                    <source>Stats</source>
                    <formula>Scores.Avg</formula>
                    <comments>The avg of the whole population</comments>
                </input>
            </inputs>
        </map>
        <map>
            <name>End of Month</name>
            <outputTo>Eom</outputTo>
            <outputType>DateTime</outputType>
            <comments>the last date of the month when the test was taken</comments>
            <inputs>
                <input>
                    <source>test</source>
                    <formula>DateTaken</formula>
                    <comments>Must be the month where the test was taken</comments>
                </input>
            </inputs>
        </map>
        <map generate-code="true">
            <name>Next Test Probability</name>
            <outputTo>NextTestProb</outputTo>
            <outputType>decimal</outputType>
            <comments></comments>
            <formula>testScore * stdScore</formula>
            <inputs>
                <input>
                    <source>test</source>
                    <formula>Score</formula>
                    <referenceName>testScore</referenceName>
                </input>
                <input>
                    <source>Stats</source>
                    <formula>Scores.StdScore</formula>
                    <comments></comments>
                    <referenceName>stdScore</referenceName>
                </input>
            </inputs>
        </map>

        <map generate-code="true">
            <outputTo>FinalScore</outputTo>
            <outputType>decimal</outputType>
            <formula>test.MyScore</formula>
            <example>12.0</example>
        </map>
    </maps>
</mapper>
